on: 
  schedule:
    - cron: '13 * * * *'
jobs:
  build_rmd_site:
    runs-on: ubuntu-latest
    name: Build Rmd Site
    steps:
    - name: Checkout current repo
      uses: actions/checkout@v2
      with:
        path: repo
        repository: 'averissimo/r-analysis-covid19'
        token: ${{ secrets.token }}
    - name: Get current directory and files
      run: |
        pwd
        ls repo
    - name: Build html
      uses: averissimo/buid-r-docker-action@master
    - name: Checkout current repo
      uses: actions/checkout@v2
      with:
        path: repo_current
        token: ${{ secrets.token }}
    - name: Move
      run: |
        ls
        rm -rf repo_current/docs
        sudo chown $UID:$UID -R repo/docs-export
        mv repo/docs-export repo_current/docs
    - name: Commit changes
      run: |
        cd repo_current
        ls
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs
        echo "number of commits since 00:01 $(git log --oneline --since='00:01' | wc -l)"
        if [ "$(git log --oneline --since='00:01' | wc -l)" -gt 0 ] && $(git log -n 1 --oneline | grep -q 'Update site (automatic)'); then
          echo "ammending"
          git commit --amend -m "Update site (automatic)" || echo "Nothing to update"
        else
          echo "new commit"
          git commit -m "Update site (automatic)" || echo "Nothing to update"
        fi
        git status
    - name: Push changes
      uses: ad-m/github-push-action@fe38f0a751bf9149f0270cc1fe20bf9156854365
      with:
        directory: repo_current
        force: true
        repository: averissimo/covid19-analysis
        github_token: ${{ secrets.token }}
